travis:
  secure:
    BINSTAR_TOKEN: hMeeayTcsNc4pT4BoDYc11S1LRQVayDwo7nEFw9puzD9FSN+yce8WXS8ODIYnt/lCy1KYUDwgruRSvh2JkxVH1a7oh2wlQXTwSHfr3xHuLNn0nrhIKjotYW5DEY/X6PQJu7rf2pcn5UKYbqIrlIFYjkO87n1MkBGhVnTJtfA8ZLcw60oydfJL/lDg7uUTqYYxxpYgEyx1BXCKuHZU4Wzw4Itcx0GgHyEFi+sOyq3u80OfVGENoX3OJfFpz30ukKn9sDziCTg5sfSHkhnYNRPT3U4UZ5KHTkihMk6kU9kNr61CH/ujK4MS5hUdWtpXfkR7fvpCMm9GbvVm+Sxt8BjwCnMp++DZNlrxLVtEzVreowU02kZL7lmwu/TYqmaSKi5+Avi71nS+bbysiXbprelmDut08uFr3Hlz2Jlg5uQp3iwfD5vvw4zP/poZQze7FKl96yZSgDGwhSIKAgMFBG/WYor4YgUR1FDPCRJoTN4Y820BaIkLeBdkxUH19D9IpSSnyEmfrS+/p5cxbZGZHzzTDcZxMPFZWgKsG1CWgImQv2iJEwq3a49Nop/zVDkAdUKab0ayDeoeG5FGl1PCIyBYhoXQasCoGWNaXHsZQFwaIfWCJBOr42XB2aDyDJT86fsBnlTM2WySfNgscHRmwjCZ8HRK1fDud3gIgGUsZce4Co=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
